[workspace]
members = [
    "ttmpv-engine",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Witt Kung <witt.w.kung@gmail.com>"]
license = "BSD-3-Clause OR Apache-2.0"
repository = "https://github.com/wittkung/ttmpv"
edition = "2021"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 16
panic = "unwind"
strip = true

[profile.test]
opt-level = 2
debug = 1
